### ISSUE TITLE
Incorrect info on `agent.filesystem` page

### ISSUE THREAD

**Issue by narcher7** [rackerlabs/docs-cloud-monitoring#11]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [x] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Product Feedback](https://feedback.rackspace.com/) website. 

**Tell us more about your issue**

A support linux admin caught this incorrect information on this page: https://github.com/rackerlabs/docs-cloud-monitoring/blob/master/api-docs/tech-ref-info/check-types/agent-check-type-ref.rst#id7     

In the “agent.filesystem” documentation has a table with the following entries:
        
            ---------------------------------------------------------------------------------------------------------------
        …
            avail 	Available space on the filesystem in kilobytes, including reserved space.
            free 	Free space available on the filesystem in kilobytes including reserved space.
        …
            ---------------------------------------------------------------------------------------------------------------
            

Which is apparently incorrect.
        
Appears the agent, agent.filesystem, uses the statvfs library:
          
       #ifdef HAVE_STATVFS
        bsize = buf.f_frsize / 512;
        #else
        bsize = buf.f_bsize / 512;
        #endif
        val = buf.f_blocks;
        fsusage->total = SIGAR_FS_BLOCKS_TO_BYTES(val, bsize);
        val = buf.f_bfree;
        fsusage->free = SIGAR_FS_BLOCKS_TO_BYTES(val, bsize);
        val = buf.f_bavail;
        fsusage->avail = SIGAR_FS_BLOCKS_TO_BYTES(val, bsize);
        fsusage->used = fsusage->total - fsusage->free;
        fsusage->files = buf.f_files;
        fsusage->free_files = buf.f_ffree;
        return SIGAR_OK;
        
        http://man7.org/linux/man-pages/man2/statvfs.2.html
        
        fsblkcnt_t     f_bfree;    /* Number of free blocks */
        fsblkcnt_t     f_bavail;   /* Number of free blocks for
                                                    unprivileged users */
            
A correct version would then look like :
            
            ---------------------------------------------------------------------------------------------------------------
        …
            avail 	Available space on the filesystem in kilobytes for normal users.
            free 	Free space available on the filesystem in kilobytes including reserved space.
        …
            ---------------------------------------------------------------------------------------------------------------

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*

**Comment by wolfdancer** [comment]
@rphillips can you provide some insights to the "avail" metrics in filesystems?  Based on this issue, the feedback seems to be that "normal users" means "not including reserved space"?  Thanks

**Comment by wolfdancer** [comment]
FYI I have talked to @rphillips over the video and got the answer. PR #13 is good to be merged and I'll comment on that PR with the same message.  But please leave this issue open. I'll submit anther PR to add clarification of these.

**Comment by narcher7** [comment]
Closed by PR #17
