### ISSUE TITLE
Convert Server-side monitoring configuration to how-to article

### ISSUE THREAD

**Issue by wolfdancer** [rackerlabs/docs-cloud-monitoring#14]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [x] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Tell us more about your issue**
I thought we converted the blog post to documentation but I cannot find it anywhere.  We should have a how-to article on the Server-side Monitoring Configuration feature so that we can keep it up-to-date.

http://blog.rackspace.com/monitor-like-a-pro-with-server-side-configuration

**Comment by narcher7** [comment]
@wolfdancer: You want to post this in https://github.com/rackerlabs/rackspace-how-to/issues and I can close it here?

**Comment by wolfdancer** [comment]
@DonNateR got it.  Moved it to https://github.com/rackerlabs/rackspace-how-to/issues/1689.  Cheers
