### ISSUE TITLE
HTML code shown on page as text

### ISSUE THREAD

**Issue by Maxim-Mazurok** [rackerlabs/docs-cloud-monitoring#24]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [X] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*

In Rackspace Monitoring documentation, on [Install and configure the agent](https://developer.rackspace.com/docs/rackspace-monitoring/v1/getting-started/install-configure/#run-the-agent-setup-program) page, in section "Run the agent setup program", after 

> On Windows, the agent location depends on the version of the agent installed and the architecture of the operating system. 

before 

> If you are using PowerShell, precede the path with an ampersand (&).

there is HTML code shown as text: 

> style="margin-left: 0.5in; margin-right: 0.5in;">

HTML source of this fragment:
```
<blockquote>
<div><p>style=&quot;margin-left: 0.5in; margin-right: 0.5in;&quot;&gt;</p>
</div></blockquote>
```
It seems like it caused by `>` in `<p>` tag. There should be space ` ` instead of `>`, then this HTML will be valid and will not be escaped as regular text.

**Comment by cyrichardson** [comment]
Thanks for reporting this bug, @Maxim-Mazurok!
