### ISSUE TITLE
Changing the label of an Entity is not allowed for customers

### ISSUE THREAD

**Issue by kruzda** [rackerlabs/docs-cloud-monitoring#26]
## What do you want us to know about?  
https://developer.rackspace.com/docs/rackspace-monitoring/v1/api-reference/entities-operations/#update-an-entity-by-id

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [x] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*

**Comment by cyrichardson** [comment]
@wolfdancer Please provide the correct content when you have a chance. Thanks!
