### ISSUE TITLE
Add in link to describe unix style load

### ISSUE THREAD

**Issue by joesavak** [rackerlabs/docs-cloud-monitoring#29]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [X] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*

In https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#agent-load-average, it'd be helpful to include a link to https://support.rackspace.com/how-to/checking-system-load-on-linux/ describing the commands we use to get unix-style load.

**Comment by cyrichardson** [comment]
@joesavak Will get to this soon.

**Comment by joesavak** [comment]
@cyrichardson  - thank you & thanks for being so responsive!
