### ISSUE TITLE
fstab description not complete

### ISSUE THREAD

**Issue by joesavak** [rackerlabs/docs-cloud-monitoring#32]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [X] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*

The description of fstab in the table on: https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#hostinfo-check-type-ref is incomplete. It hsould read: "Reads /etc/fstab and retrieves information about the file system configuration"

**Comment by cyrichardson** [comment]
@joesavak Will get this taken care of today and back to you for review before merging.
