### ISSUE TITLE
Clarify YAML array syntax for agent.plugin checks via config file

### ISSUE THREAD

**Issue by itzg** [rackerlabs/docs-cloud-monitoring#37]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [x] Bug (misspellings, grammatical problems, broken link, format issues)
- [x] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

On the page/section https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/server-side-agent-config-yaml/#agent-plugin-check

![image](https://user-images.githubusercontent.com/988985/29638982-bd5cdf08-881e-11e7-8bd9-fac78015e0bc.png)

1. The blog link is not linked properly
2. While supporting a user I realized it would be helpful to clarify that YAML array/list/sequences require a comma separated list inside the square brackets. Passing a space separated list would seem intuitively correct, but results in a single argument passed to the script specified by `file`.

**Comment by cyrichardson** [comment]
Please review changes based on issue #37 at 
https://staging.developer.rackspace.com/build-1d0dc93f61/docs/rackspace-monitoring/v1/tech-ref-info/server-side-agent-config-yaml/ and let me know if #38 can be merged.

**Comment by cyrichardson** [comment]
@itzg ^^

**Comment by itzg** [comment]
The changes in #38 look perfect. Thanks.
