### ISSUE TITLE
MaaS API / Create Suppression formatting/info

### ISSUE THREAD

**Issue by aaronsegura** [rackerlabs/docs-cloud-monitoring#39]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [x] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

The information under "Create Suppression" in the MaaS API Docs (https://developer.rackspace.com/docs/rackspace-monitoring/v1/api-reference/suppressions-operations/#id14) needs a little love.

- in the response code table, the 201 result code name doesn't make sense
- the "response" section is filled with more request examples instead of information regarding response info

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*

**Comment by cyrichardson** [comment]
@toxick Thanks for the doc issue report! I'll make a change shortly and request your review.

**Comment by cyrichardson** [comment]
@toxick Can you please provide an example response for creating a suppression? It looks like all the over post-create methods do not return a response body. If that is true for creating a suppression, can you please confirm? Thanks!

**Comment by aaronsegura** [comment]
Hi Catherine - There isn't a response, but the documentation has a
'response' heading in that section and lists a bunch of example *requests*
underneath it.

**Comment by cyrichardson** [comment]
Thanks, @toxick. PR #40 should take care of it then. I moved the Response heading under the request examples, deleted a duplicate request example, and add the sentence under the Response heading that no response body is returned. Please take a look at the PR and if you approved, I'll merge it.
