### ISSUE TITLE
MySQL server-side replication check example

### ISSUE THREAD

**Issue by inflatador** [rackerlabs/docs-cloud-monitoring#44]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [X ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

No example for MySQL server side configuration file. Here's an example. Note that the monitor user ("raxmon") needs the REPLICATION CLIENT grant in MySQL.

```
type    : agent.mysql
label   : mysql_replication
period  : 60
timeout : 10
disabled: false
details:
  host: 192.168.100.1
  port: 3306
  username: raxmon
  password: your_password_here

alarms  :
    MySQL-replication:
        label: MySQL replication check
        notification_plan_id: npTechnicalContactsEmail
        criteria: |
            if (metric['replication.slave_sql_running'] != "Yes") {
            return new AlarmStatus(CRITICAL, 'Replica SQL thread is not
            running with error number #{replication.last_errno} . ');
            }
            if (metric['replication.slave_io_running'] != "Yes") {
            return new AlarmStatus(CRITICAL, 'Replica IO thread is not
            running with error number #{replication.last_io_errno} and
            error message #{replication.last_io_error}.');
            }
            return new AlarmStatus(OK, "Replica SQL and I/O threads are
            running");
```

**Comment by cyrichardson** [comment]
@inflatador Will create PR for your review.

**Comment by cyrichardson** [comment]
@inflatador Can you please provide a suggested placement for this in the existing monitoring docs?

**Comment by inflatador** [comment]
Hello, this belongs in the 

https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/server-side-agent-config-yaml/ section along with the other YAML file examples.

Thanks so much for your quick response!

**Comment by cyrichardson** [comment]
Thank YOU!

**Comment by cyrichardson** [comment]
@inflatador Please review PR #45 and provide your feedback. Thank you!

https://staging.developer.rackspace.com/build-ab733c0852/docs/rackspace-monitoring/v1/tech-ref-info/server-side-agent-config-yaml/#mysql-check-alarm
