### ISSUE TITLE
I see *dead page*.

### ISSUE THREAD

**Issue by mritunjaykumar** [rackerlabs/docs-cloud-monitoring#46]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [X] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**
I see *dead page* on https://developer.rackspace.com/docs/rackspace-monitoring/v1/api-reference/check-operations/#check-operations
Under "Create a check" section: Create a new check in the monitoring system by using a valid set of attributes from the checks attributes table. For a tutorial on creating some basic checks, see *Create checks* in the Rackspace Cloud Monitoring Getting Started Guide.
"Create checks" link is giving "Page Not Found" error.

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*
<img width="812" alt="screen shot 2017-11-14 at 5 30 44 pm" src="https://user-images.githubusercontent.com/7436029/32814602-dc452a38-c964-11e7-9f68-2cd9c5055fd8.png">

**Comment by cyrichardson** [comment]
@mritunjaykumar Link fixed. Please provide your review/feedback. Thank you!

https://staging.developer.rackspace.com/build-a7172bfcb8/docs/rackspace-monitoring/v1/api-reference/check-operations/#create-a-check
