### ISSUE TITLE
Issues with dedicated Windows Rackspace Monitoring installation

### ISSUE THREAD

**Issue by daemontroll** [rackerlabs/docs-cloud-monitoring#49]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [ x] Missing information
- [ x] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**
During the installation guides that I came across there were numerous issues.
 
First for dedicated you can't run the auto install as there is no cloud username.

     There is no mention of auto install for Windows in the API docs. Added link to
     How-To article https://support.rackspace.com/how-to/install-and-configure-the-rackspace-monitoring-agent/

Second when it comes to doing the install for Windows once the agent is installed the location of the config file and the .yaml files are not clearly documented.  The config file should be C:\ProgramData\Rackspace Monitoring\config\rackspace-monitoring-agent.cfg.

      Change made in "Configure the agent" section: configuration to config.

Third once the agent is installed a directory is created called rackspace-monitoring-agent.conf.d at the location C:\ProgramData\Rackspace Monitoring\config\rackspace-monitoring-agent.conf.d.  This is where the .yaml files are stored.

   This is noted in the section "Use a server-side configuration YAML file: 
    -  Save the YAML file in the ``rackspace-monitoring-agent.conf.d``
        subdirectory under the ``config`` directory:

      *(Windows)*
      ``C:\ProgramData\Rackspace Monitoring\config\rackspace-monitoring-agent.conf.d``.

Fourth it is not clear what the name of the files should be, but they can be anything that you want just ends in .yaml.
 
   Added the following to the section "Configuring the agent with YAML files": 
   "You can name YAML files as you like, but they must end in
    ``.yaml``."

Fifth it clearly shows what the Linux files should contain but not the Windows ones.  For Windows you can pull what the Targets are but it returns results that are not clear.  For Windows network it would be the friendly name of the network interface.  For the Windows disk it would be C:\ or D:\.

   Added a note in the discussion abou the YAML files as follows:
  "For Windows, the files should have the name of the network interface force
  the Windows network, and ``C:\`` or ``D:\`` for the Windows disk. "

*Be as specific as possible. Include excerpts from the text or a screen capture when necessary.*

**Comment by cyrichardson** [comment]
@daemontroll Thanks for this information. I will add this task to the InfoDev sprint.

FYI: https://support.rackspace.com/how-to/install-and-configure-the-rackspace-monitoring-agent/

**Comment by cyrichardson** [comment]
@daemontroll Did you see this article on the support.rackspace.com site? https://support.rackspace.com/how-to/install-and-configure-the-rackspace-monitoring-agent/
Did it help with any of your questions? Do you think your questions should be addressed in the article at the link above, in the cloud monitoring developer guide, or both? Thanks!
