### ISSUE TITLE
New REST calls for our upcoming Private Network Monitoring feature

### ISSUE THREAD

**Issue by itzg** [rackerlabs/docs-cloud-monitoring#52]
## What do you want us to know about?  

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [x] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Tell us more about your issue**

Hi, we're working on GA'ing a new feature in MaaS called Private Network Monitoring. To facilitate use of the new feature we have added new create, update, delete operations for `monitoring_zones`. In this context the user is creating/updating/deleting "private" monitoring zones that exist alongside the existing public zones (such as `mziad`, `mzdfw`, ...).

The new calls are:
* `POST /monitoring_zones`
* `PUT /monitoring_zones/{monitoringZoneId}`
* `DELETE /monitoring_zones/{monitoringZoneId}`

[This gist](https://gist.github.rackspace.com/geof0549/febf476c23277e627c6c9875699b42a0) contains an HTML rendering of Swagger/OpenAPI specification, also located there as the YML file. That API info details the parameters and successful response of the new calls. What is not shown are the typical failure scenarios 400, 401, 403, 500, 503, but would need to be included in the final documentation.

Please let me or Carolyn Rivas (product manager) if you have any questions, need more information, etc.

Thanks.

**Comment by cyrichardson** [comment]
@itzg Thank you for opening this doc issues. It's been added to INFODEV Sprint 18 (3/28-4/11). 

https://jira.rax.io/browse/INFODEV-1354

When a draft is ready, it will be sent to you for review.

**Comment by cyrichardson** [comment]
Closed by #53
