### ISSUE TITLE
New Ubuntu and Debian repositories

### ISSUE THREAD

**Issue by itzg** [rackerlabs/docs-cloud-monitoring#56]
## What do you want us to know about?  

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [x] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [ ] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

**Tell us more about your issue**

I just realized that we have added several new Ubuntu releases to our repositories, but the team must have forgotten to relay the updates to the documentation. In fact, rather than list out a command per release, I would recommend we use a "smarter" script snippet that works on all of our supported Ubuntu releases.

On this page

https://developer.rackspace.com/docs/rackspace-monitoring/v1/getting-started/install-configure/#install-agent-step-by-step

### Please change step 1 of the Ubuntu section

![image](https://user-images.githubusercontent.com/988985/40059881-dadc3e3a-581a-11e8-971d-102c47b94a78.png)

### ...to the following

1. Run the WHOLE COMMAND shown here, without line breaks, to add the monitoring agent package repository to APT:

```
sudo sh -c "echo 'deb http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-$(lsb_release -rs)-x86_64 cloudmonitoring main' > /etc/apt/sources.list.d/rackspace-monitoring-agent.list"
```

**Comment by cyrichardson** [comment]
Thanks, @itzg. I'll get a patch together for your review.

**Comment by itzg** [comment]
You're always so prompt, thanks! FYI I have submitted for the same change to be made to the corresponding Intelligence UI page.
