### ISSUE TITLE
Alarms API documentation incorrect for disabled property

### ISSUE THREAD

**Issue by FarajiA** [rackerlabs/docs-cloud-monitoring#61]
## What do you want us to know about?  
*(Check all that apply.)*

**Report a documentation issue**
- [x] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug 
- [x] Product feedback

**Note:** For product-related issues, you can also submit an issue from the [Rackspace Community Forum](https://community.rackspace.com/) website. 

I noticed the wording for Alarms is incorrect.
https://developer.rackspace.com/docs/rackspace-monitoring/v1/api-reference/alarms-operations

The disabled property states that it "Disables the check", it in fact disables the actual alarm. The Check is disabled via the property of the same name located in [Checks API](https://developer.rackspace.com/docs/rackspace-monitoring/v1/api-reference/check-operations/)

![alarmapi](https://user-images.githubusercontent.com/5041718/45900686-16d3cc00-bda6-11e8-828f-f5739dd6399d.png)

Thanks.

**Comment by cyrichardson** [comment]
@FarajiA Thanks for opening an issue to fix the docs! Please review PR #62 and provide your feedback.

**Comment by cyrichardson** [comment]
#62 fixes this issue.
