### ISSUE TITLE
Align supported agent installation platforms

### ISSUE THREAD

**Issue by itzg** [rackerlabs/docs-cloud-monitoring#77]
## What do you want us to know about?  

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [ ] Missing information
- [x] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug
- [ ] Product feedback

**Tell us more about your issue**

We realized we haven't been doing a good job of coordinating new platforms and deprecated platforms for the agent installations described at

https://developer.rackspace.com/docs/rackspace-monitoring/v1/getting-started/install-configure/

Here are a set of changes that will get the documentation back in alignment with our supported platforms:

Distribution | Remove | Add | Notes
---|---|---|---
Debian | wheezy, testing, unstable | buster, jessie | Resulting list will be buster, stretch, jessie
Redhat | 5 | |
CentOS | 5 | |
Fedora | 16 - 21 | 22 - 30 |

Thanks!

**Comment by cyrichardson** [comment]
@itzg Can you please provide content for the buster and jessie additions to Debian? Thank you!

**Comment by cyrichardson** [comment]
@itzg Can you please provide content for 22-20 additions to Fedora? Thank you!

**Comment by itzg** [comment]
They're all "copy-paste-replace" duplicates, so the content for each would be:

## Debian buster

```
sudo sh -c 'echo "deb http://stable.packages.cloudmonitoring.rackspace.com/debian-buster-x86_64 cloudmonitoring main" > /etc/apt/sources.list.d/rackspace-monitoring-agent.list'
```

## Debian jessie

```
sudo sh -c 'echo "deb http://stable.packages.cloudmonitoring.rackspace.com/debian-jessie-x86_64 cloudmonitoring main" > /etc/apt/sources.list.d/rackspace-monitoring-agent.list'
```

## Fedora 22

### Step 1
```
curl https://monitoring.api.rackspacecloud.com/pki/agent/fedora-22.asc > /tmp/signing-key.asc
sudo rpm --import /tmp/signing-key.asc
```

### Step 2
```
[rackspace]
name=Rackspace Monitoring
baseurl=http://stable.packages.cloudmonitoring.rackspace.com/fedora-22-x86_64
enabled=1
```

## Fedora 23 - 30

_Same as above but replace "22" with the respective release number_

**Comment by cyrichardson** [comment]
Thank you, @itzg. On those changes now.
