### ISSUE TITLE
Add libmysqlclient-dev note for agent.mysql plugin

### ISSUE THREAD

**Issue by itzg** [rackerlabs/docs-cloud-monitoring#81]
## What do you want us to know about?  

**Report a documentation issue**
- [ ] Bug (misspellings, grammatical problems, broken link, format issues)
- [x] Missing information
- [ ] Incorrect information
- [ ] Feedback or suggestions
- [ ] Other

**Product**
- [ ] Product bug
- [ ] Product feedback

**Tell us more about your issue**

In the agent.mysql section (https://developer.rackspace.com/docs/rackspace-monitoring/v1/tech-ref-info/check-type-reference/#agent-mysql) it should include a note alongside the existing one that states something like:

> The libmysqlclient-dev package should be installed, if not already present, on the host where the agent.mysql plugin will be running.

Thanks.

**Comment by cyrichardson** [comment]
Fixed by #82
